const LABELS: Record<string, string> = {
  "lead.followup.schedule": "تحديد موعد متابعة العميل",
  "lead.followup.complete": "إتمام متابعة العميل وتسجيل التواصل",
  "lead.followup.cancel": "إلغاء موعد متابعة العميل",
  "lead.converted_from_messenger": "تحويل محادثة إلى عميل محتمل",
  "lead.updated": "تعديل بيانات العميل",
  "lead.assigned": "إسناد العميل لعضو الفريق",
  "post.created": "إنشاء منشور", "post.updated": "تعديل منشور", "post.duplicated": "تكرار منشور", "post.restored": "استرجاع نسخة",
  "post.queued": "إضافة للطابور", "post.rescheduled": "نقل موعد", "post.retry": "إعادة محاولة النشر", "post.submitted": "إرسال للمراجعة",
  "post.approved": "موافقة", "post.rejected": "رفض", "post.changes_requested": "طلب تعديل", "post.publish_now": "نشر فوري", "auth.login": "تسجيل دخول", "user.created": "إضافة مستخدم", "user.updated": "تعديل مستخدم", "post.note_added": "ملاحظة داخلية", "post.purged": "حذف نهائي",
  "post.restored_from_trash": "استرجاع من السلة", "post.bulk.schedule": "جدولة جماعية", "post.bulk.to_draft": "نقل جماعي لمسودة",
  "post.bulk.unschedule": "إلغاء جدولة جماعي", "post.bulk.archive": "أرشفة جماعية", "post.bulk.delete_drafts": "حذف مسودات",
  "post.bulk.change_page": "تغيير الصفحة", "post.bulk.assign_campaign": "ربط بحملة", "queue.reordered": "إعادة ترتيب الطابور",
  "queue.slots_updated": "تعديل أوقات الطابور", "template.created": "إنشاء قالب", "template.updated": "تعديل قالب", "template.deleted": "حذف قالب",
  "media.uploaded": "رفع صورة", "media.added": "إضافة صورة", "media.deleted": "حذف صورة", "campaign.created": "إنشاء حملة", "campaign.updated": "تعديل حملة",
  "import.committed": "استيراد ملف", "recurrence.created": "إنشاء تكرار", "recurrence.stopped": "إيقاف تكرار", "recurrence.materialized": "إنشاء مواعيد متكررة",
  "goal.saved": "حفظ هدف", "goal.deleted": "حذف هدف", "export.downloaded": "تصدير", "library.created": "إضافة للمكتبة", "library.converted": "تحويل لمسودة",
  "library.updated": "تعديل عنصر مكتبة", "library.deleted": "حذف من المكتبة", "settings.notifications_updated": "تعديل الإشعارات",
  "settings.approval_updated": "تعديل سير الموافقة", "settings.publishing_rules_updated": "تعديل قواعد النشر",
};
export const auditLabel = (action: string) => LABELS[action] ?? action;
