"use client";
import { useCallback,useEffect,useState } from "react";
import { inboxFilterSchema,type InboxFilter } from "@/services/comments/filters";
type Catalog={pages:Array<{id:string;name:string}>;users:Array<{id:string;name:string;email:string}>;tags:Array<{id:string;name:string}>;views:Array<{id:string;name:string;filter:InboxFilter}>};
export function InboxControls({filter,onChange}:{filter:InboxFilter;onChange:(filter:InboxFilter)=>void}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[name,setName]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const response=await fetch("/api/comments?view=catalog");if(!response.ok)throw new Error("تعذر تحميل الفلاتر");setCatalog(await response.json());}catch(e){setError(e instanceof Error?e.message:"تعذر التحميل");}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 const change=(key:keyof InboxFilter,value:string)=>onChange({...filter,[key]:value});
 const save=async()=>{const response=await fetch("/api/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_view",name,filter})});if(response.ok){setName("");await load();}else setError("تعذر حفظ العرض");};
 return <details className="comment-filters"><summary>الفلاتر والعروض المحفوظة</summary>{error&&<p role="alert">{error}</p>}<div className="comment-filter-grid"><label>الصفحة<select value={filter.page} onChange={e=>change("page",e.target.value)}><option value="">كل الصفحات</option>{catalog?.pages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>معرّف المنشور<input value={filter.post} onChange={e=>change("post",e.target.value)}/></label><label>من تاريخ<input type="date" value={filter.from} onChange={e=>change("from",e.target.value)}/></label><label>إلى تاريخ<input type="date" value={filter.to} onChange={e=>change("to",e.target.value)}/></label><label>المسؤول<select value={filter.assigned} onChange={e=>change("assigned",e.target.value)}><option value="">الكل</option><option value="unassigned">غير مسند</option>{catalog?.users.map(u=><option key={u.id} value={u.id}>{u.name??u.email}</option>)}</select></label><label>الوسم<select value={filter.tag} onChange={e=>change("tag",e.target.value)}><option value="">كل الوسوم</option>{catalog?.tags.map(t=><option key={t.id}>{t.name}</option>)}</select></label><label>نوع الرد<select value={filter.replyType} onChange={e=>change("replyType",e.target.value)}><option value="">الكل</option><option value="manual">يدوي</option><option value="template">قالب</option><option value="automation">آلي</option><option value="ai_assisted">بمساعدة AI</option></select></label><label>التصنيف<select value={filter.sentiment} onChange={e=>change("sentiment",e.target.value)}><option value="">الكل</option><option value="complaint">شكاوى</option><option value="price">استفسارات سعر</option><option value="purchase">شراء</option><option value="positive">إيجابية</option></select></label><label>معرّف قاعدة الأتمتة<input value={filter.rule} onChange={e=>change("rule",e.target.value)}/></label></div><div className="comments-toolbar"><input aria-label="اسم العرض المحفوظ" placeholder="اسم العرض المحفوظ" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name.trim()} onClick={save}>حفظ العرض</button><button onClick={()=>onChange(inboxFilterSchema.parse({}))}>مسح الفلاتر</button></div><div className="comments-links"><button onClick={()=>onChange(inboxFilterSchema.parse({status:"needs_reply"}))}>تحتاج ردًا</button><button onClick={()=>onChange(inboxFilterSchema.parse({sentiment:"complaint"}))}>الشكاوى</button><button onClick={()=>onChange(inboxFilterSchema.parse({sentiment:"price"}))}>السعر</button>{catalog?.views.map(v=><button key={v.id} onClick={()=>onChange(v.filter)}>{v.name}</button>)}</div></details>;
}
type Analytics={total:number;answered:number;unanswered:number;responseRate:number|null;keywords:Array<{word:string;count:number}>;byPost:Array<{post_id:string|null;count:number;content:string|null}>;byRule:Array<{id:string;name:string;matched:number;skipped:number;replied:number;failed:number;human_review:number}>};
export function CommentsAnalytics(){const [data,setData]=useState<Analytics|null>(null),[error,setError]=useState("");useEffect(()=>{fetch("/api/comments?view=analytics").then(async r=>{if(!r.ok)throw new Error();setData(await r.json());}).catch(()=>setError("تعذر تحميل التحليلات"));},[]);return error?<p role="alert">{error}</p>:!data?<p>جارٍ تحميل التحليلات…</p>:<div className="comments-settings-grid"><section className="panel-card"><h2>نسبة الاستجابة</h2><p>{data.responseRate===null?"لا توجد بيانات":`${data.responseRate}%`} · {data.answered} تعليقًا تم الرد عليه · {data.unanswered} دون رد</p><h3>أكثر الكلمات تكرارًا</h3>{data.keywords.length?data.keywords.map(k=><div className="integration-row" key={k.word}><span>{k.word}</span><b>{k.count}</b></div>):<p>لا توجد تعليقات للتحليل.</p>}<h3>التعليقات حسب المنشور</h3>{data.byPost.map(p=><div className="integration-row" key={p.post_id??"unknown"}><span>{p.content?.slice(0,80)??p.post_id??"منشور غير متاح"}</span><b>{p.count}</b></div>)}</section><section className="panel-card"><h2>أداء قواعد الأتمتة</h2>{data.byRule.length?data.byRule.map(r=><article className="comment-template" key={r.id}><h3>{r.name}</h3><p>مطابقات {r.matched} · ردود {r.replied} · متخطاة {r.skipped} · فاشلة {r.failed} · مراجعة {r.human_review}</p><small>نجاح الإرسال: {r.replied+r.failed>0?`${Math.round(r.replied/(r.replied+r.failed)*100)}%`:"لا توجد محاولات إرسال"}</small></article>):<p>لا توجد قواعد بعد.</p>}</section></div>;}
