"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { RuleManager } from "./rule-manager";
import { useCallback,useEffect,useState } from "react";
import type { CommentsCapabilities } from "@/services/comments/provider";
import { InboxControls,CommentsAnalytics } from "./advanced-controls";
import { inboxFilterSchema,type InboxFilter } from "@/services/comments/filters";
import { canComment,type CommentRole } from "@/services/comments/permissions";
type Comment={id:string;message:string;author_name:string|null;author_id:string|null;author_avatar:string|null;page_name:string;page_id:string;post_id:string|null;created_time:string;status:string;sentiment:string;facebook_comment_id:string;needs_reply:boolean};
type Reply={id:string;content:string;status:string;reply_type:string;created_at:string};
type Template={id:string;name:string;content:string;category:string;active:boolean;usage_count:number};
type Detail={comment:Comment;thread:Comment[];replies:Reply[];notes:Array<{id:string;body:string;author:string}>;tags:Array<{id:string;name:string}>;users:Array<{id:string;name:string;email:string}>;post:{id:string;content:string;campaign_name:string|null}|null;history:Comment[];authorTotal:number|null};
type Metrics={today:number;total:number;needs_reply:number;replied:number;failed:number;sent:number;manual:number;automated:number;avg_response_seconds:number|null;lastSync:{status:string;started_at:string;error_code:string|null}|null;lastComment:string|null};
type Caps=CommentsCapabilities&{safeMode:boolean;realRepliesEnabled:boolean};
const labels:Record<string,string>={all:"الكل",unread:"غير المقروءة",needs_reply:"تحتاج ردًا",replied:"تم الرد",important:"المهمة",hidden:"المخفية",spam:"المزعجة",resolved:"محلولة",new:"جديدة",failed:"فاشلة",draft:"مسودة",approved:"معتمد",pending_approval:"بانتظار الموافقة",sent:"أُرسل",neutral:"محايد",price:"استفسار سعر",purchase:"رغبة شراء",question:"سؤال",complaint:"مراجعة بشرية",positive:"إيجابي"};
const time=(value:string)=>new Intl.DateTimeFormat("ar-SA",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(value));
async function api<T>(query:string,body?:unknown):Promise<T>{const response=await fetch(`/api/comments${query}`,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const data=await response.json();if(!response.ok)throw new Error(data.error??data.code??"تعذر الاتصال");return data;}
export function CommentsClient({mode="inbox"}:{mode?:"inbox"|"templates"|"rules"|"analytics"|"status"}){
  const router=useRouter();
  const [systemAdmin,setSystemAdmin]=useState(false);
  const [filter,setFilter]=useState<InboxFilter>(()=>inboxFilterSchema.parse({}));
  const [role,setRole]=useState<CommentRole>("viewer"),[actor,setActor]=useState("");
  const [quickSearch,setQuickSearch]=useState("");
  const [items,setItems]=useState<Comment[]>([]);const [caps,setCaps]=useState<Caps|null>(null);const [metrics,setMetrics]=useState<Metrics|null>(null);const [templates,setTemplates]=useState<Template[]>([]);
  const [detail,setDetail]=useState<Detail|null>(null);const [status,setStatus]=useState("all");const [query,setQuery]=useState("");const [cursor,setCursor]=useState<string|null>(null);const [selected,setSelected]=useState<string[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
  const [content,setContent]=useState("");const [templateId,setTemplateId]=useState<string|null>(null);const [note,setNote]=useState("");const [tag,setTag]=useState("");
  const [editTemplate,setEditTemplate]=useState<Template|null>(null);const [name,setName]=useState("");const [text,setText]=useState("");const [category,setCategory]=useState("عام");
  const load=useCallback(async()=>{
    const me=await api<{role:CommentRole;email:string;systemAdmin:boolean}>("?view=me").catch(()=>null);if(!me){setError("الجلسة منتهية أو الحساب معطّل؛ سجّل الدخول مجددًا");setLoading(false);return;}setRole(me.role);setActor(me.email);setSystemAdmin(me.systemAdmin);
    const results=await Promise.allSettled([api<Caps>("?view=capabilities"),api<Metrics>("?view=metrics"),api<Template[]>("?view=templates")]);
    if(results[0].status==="fulfilled")setCaps(results[0].value);if(results[1].status==="fulfilled")setMetrics(results[1].value);if(results[2].status==="fulfilled")setTemplates(results[2].value);
    const failed=results.find(r=>r.status==="rejected");if(failed?.status==="rejected")setError(failed.reason instanceof Error?failed.reason.message:"تعذر تحميل البيانات");setLoading(false);
  },[]);
  const loadInbox=useCallback(async(next?:string)=>{try{const params=new URLSearchParams({...filter,status,q:query});if(next)params.set("cursor",next);const result=await api<{items:Comment[];nextCursor:string|null}>(`?${params}`);setItems(old=>next?[...old,...result.items]:result.items);setCursor(result.nextCursor);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التعليقات");}},[status,query,filter]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{if(mode!=="inbox")return;const timer=setTimeout(()=>loadInbox(),250);return()=>clearTimeout(timer);},[mode,loadInbox]);
  useEffect(()=>{if(mode!=="inbox")return;const timer=setInterval(()=>{if(!document.hidden)void loadInbox();},60000);return()=>clearInterval(timer);},[mode,loadInbox]);
  const open=async(id:string)=>{try{setDetail(await api<Detail>(`?id=${id}`));setContent("");setTemplateId(null);setError("");}catch(e){setError(e instanceof Error?e.message:"تعذر فتح التعليق");}};
  const mutate=async(body:unknown)=>{const action=typeof body==="object"&&body&&"action" in body?String(body.action):"";if(!canComment(role,action)){setError("الدور الحالي لا يسمح بهذا الإجراء");return;}setBusy(true);setError("");setNotice("");try{await api("",body);setNotice("تم الحفظ داخل النظام. لم يُرسل أي رد إلى Facebook.");await load();if(mode==="inbox")await loadInbox();if(detail)await open(detail.comment.id);}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");}finally{setBusy(false);}};
  const resetTemplate=()=>{setEditTemplate(null);setName("");setText("");setCategory("عام");};
  return <div className="comments-page">
    <header className="comments-heading"><div><small>إدارة المحادثات · Facebook</small><h1>{mode==="inbox"?"صندوق الوارد":mode==="templates"?"قوالب الردود":mode==="rules"?"أتمتة التعليقات":mode==="analytics"?"تحليلات التعليقات":"حالة التعليقات"}</h1><p>كل المحادثات في مكان واحد، مع موافقات وحماية من الرد المتكرر.</p></div><span className="comments-safe">● الردود الحقيقية متوقفة</span></header>
    <nav className="comments-links"><Link href="/inbox">صندوق الوارد</Link><Link href="/settings/replies">قوالب الردود</Link><Link href="/automations/comments">القواعد</Link><Link href="/analytics/comments">التحليلات</Link></nav>
    <div className="comments-links"><small>{actor} · {role==="admin"?"مدير":role==="editor"?"محرر":"مشاهد"}</small>{systemAdmin&&<Link href="/settings/comment-team">إدارة الفريق</Link>}{systemAdmin&&<Link href="/dashboard">لوحة التحكم</Link>}<Link href="/comments/login">دخول الفريق</Link><button onClick={async()=>{await fetch("/api/comments/auth",{method:"DELETE"});router.push("/comments/login");}}>خروج الفريق</button></div>
    {error&&<div role="alert" className="banner">{error}</div>}{notice&&<div role="status" className="comments-notice">{notice}</div>}
    {caps&&!caps.reply&&<div className="comments-capability"><strong>القراءة {caps.read?"متاحة":"غير متاحة"} · الرد غير متاح</strong><p>موصل Facebook الحالي لا يوفر صلاحية الرد على التعليقات. يمكنك إدارة المحادثات وحفظ مسودات وقوالب دون إرسال.</p><small>لا توجد أدوات إخفاء أو حذف، ولا webhook مُثبت. المزامنة الدورية متوقفة حتى توثيق حدود الاستدعاء.</small></div>}
    {loading?<p role="status">جارٍ تحميل البيانات…</p>:<>
    {(mode==="inbox"||mode==="analytics"||mode==="status")&&metrics&&<section className="comments-metrics">{[["تعليقات اليوم",metrics.today],["تحتاج ردًا",metrics.needs_reply],["ردود مرسلة",metrics.sent],["ردود فاشلة",metrics.failed]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value??0}</strong></div>)}</section>}
    {mode==="inbox"&&<>
      <InboxControls filter={{...filter,status:status as InboxFilter["status"],q:query}} onChange={value=>{setFilter(value);setStatus(value.status);setQuery(value.q);setSelected([]);}}/>
      <div className="comments-toolbar"><input aria-label="البحث في التعليقات" placeholder="ابحث بالنص، اسم الكاتب أو معرّف المنشور…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary-button" disabled={busy||!caps?.read||role!=="admin"} onClick={()=>{const now=new Date();mutate({action:"sync",from:new Date(now.getTime()-2*86400000).toISOString().slice(0,10),to:now.toISOString().slice(0,10)});}}>جلب تعليقات آخر يومين</button></div>
      <div className="comments-tabs" role="tablist">{["all","unread","needs_reply","replied","important","hidden","spam"].map(s=><button key={s} role="tab" aria-selected={status===s} className={status===s?"active":""} onClick={()=>{setStatus(s);setSelected([]);}}>{labels[s]}</button>)}</div>
      {role==="admin"&&selected.length>0&&<div className="comments-bulk"><span>{selected.length} محدد</span>{["resolved","important","spam"].map(value=><button key={value} disabled={busy} onClick={()=>mutate({action:"status",ids:selected,value})}>{labels[value]}</button>)}<button onClick={()=>setSelected([])}>إلغاء التحديد</button></div>}
      <div className={`comments-workspace ${detail?"conversation-open":""}`}>
        <section className="comments-list" aria-label="قائمة التعليقات">{items.length?items.map(item=><article key={item.id} className={detail?.comment.id===item.id?"selected":""}><input type="checkbox" aria-label={`تحديد التعليق ${item.message.slice(0,30)}`} checked={selected.includes(item.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,item.id]:old.filter(id=>id!==item.id))}/><button onClick={()=>open(item.id)}><div className="comment-row-title"><span className="comment-avatar">{item.author_name?.[0]??"؟"}</span><div><strong>{item.author_name??"هوية الكاتب غير متاحة"}</strong><small>{item.page_name}</small></div></div><p>{item.message}</p><footer><time>{time(item.created_time)}</time><span>{labels[item.status]??item.status}</span></footer></button></article>):<div className="comments-empty"><span>✉</span><h2>لا توجد تعليقات هنا</h2><p>اجلب التعليقات المتاحة من الصفحة. لن تُعرض بيانات تجريبية أو محادثات وهمية.</p></div>}{cursor&&<button className="secondary-button" onClick={()=>loadInbox(cursor)}>تحميل المزيد</button>}</section>
        <section className="comments-conversation" aria-label="المحادثة">{detail?<>
          <header><button className="comments-back" onClick={()=>setDetail(null)}>← الرجوع</button><h2>{detail.comment.author_name??"تعليق Facebook"}</h2><span>{labels[detail.comment.status]}</span></header>
          {detail.post&&<div className="comments-original"><small>المنشور الأصلي</small><p>{detail.post.content}</p><Link href={`/posts/${detail.post.id}`}>فتح المنشور</Link></div>}
          <div className="comments-messages"><div className="comment-bubble"><p>{detail.comment.message}</p><time>{time(detail.comment.created_time)}</time></div>{detail.thread.map(reply=><div className="comment-bubble" key={reply.id}><strong>{reply.author_name??"الكاتب غير متاح"}</strong><p>{reply.message}</p><time>{time(reply.created_time)}</time></div>)}{detail.replies.map(reply=><div className="comment-bubble outgoing" key={reply.id}><small>{labels[reply.status]??reply.status} · {reply.reply_type}</small><p>{reply.content}</p><time>{time(reply.created_at)}</time>{["draft","pending_approval"].includes(reply.status)&&<button disabled={busy} onClick={()=>mutate({action:"approve",id:detail.comment.id,replyId:reply.id})}>اعتماد المسودة دون إرسال</button>}</div>)}</div>
          <div className="comments-composer"><label>الرد المقترح<textarea rows={4} readOnly={role==="viewer"} value={content} onChange={e=>setContent(e.target.value)} placeholder="اكتب مسودة الرد…"/></label><input aria-label="البحث في الردود الجاهزة" placeholder="ابحث عن رد جاهز…" value={quickSearch} onChange={e=>setQuickSearch(e.target.value)}/><select disabled={role==="viewer"} aria-label="قالب الرد" value={templateId??""} onChange={e=>{const template=templates.find(t=>t.id===e.target.value);setTemplateId(template?.id??null);if(template)setContent(template.content);}}><option value="">إدراج قالب رد</option>{templates.filter(t=>t.active&&`${t.name} ${t.category} ${t.content}`.includes(quickSearch)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="row-between"><button className="secondary-button" disabled={busy||!content.trim()||role==="viewer"} onClick={()=>mutate({action:"draft",id:detail.comment.id,content,templateId})}>حفظ مسودة</button><button className="primary-button" disabled title="الموصل لا يوفر إجراء للرد">إرسال إلى Facebook غير متاح</button></div><small>الملاحظات والمسودات خاصة بالفريق؛ لا تصل إلى Facebook.</small></div>
        </>:<div className="comments-empty"><span>☷</span><h2>اختر محادثة</h2><p>اقرأ التعليق وراجعه، ثم حضّر الرد المناسب.</p></div>}</section>
        <aside className="comments-context">{detail?<><h3>تفاصيل المحادثة</h3><dl><dt>الكاتب</dt><dd>{detail.comment.author_name??"غير متاح من MCP"}</dd><dt>الصفحة</dt><dd>{detail.comment.page_name}</dd><dt>التصنيف</dt><dd>{labels[detail.comment.sentiment]??detail.comment.sentiment}</dd><dt>المنشور</dt><dd dir="ltr">{detail.comment.post_id??"غير متاح"}</dd></dl><label>حالة المحادثة<select value={detail.comment.status} disabled={busy} onChange={e=>mutate({action:"status",ids:[detail.comment.id],value:e.target.value})}>{["unread","needs_reply","resolved","important","spam"].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>إسناد إلى<select aria-label="المستخدم المسؤول" disabled={busy} onChange={e=>mutate({action:"assign",ids:[detail.comment.id],value:e.target.value})} defaultValue=""><option value="">غير مسند</option>{detail.users.map(u=><option key={u.id} value={u.id}>{u.name??u.email}</option>)}</select></label><h3>الوسوم</h3><div>{detail.tags.map(t=><span className="comment-tag" key={t.id}>{t.name}</span>)}</div><input aria-label="وسم جديد" placeholder="مثلاً: مهتم، سعر، طلب" value={tag} onChange={e=>setTag(e.target.value)}/><button disabled={busy||!tag.trim()} onClick={()=>mutate({action:"tag",ids:[detail.comment.id],value:tag})}>إضافة الوسم</button><h3>ملاحظات داخلية</h3>{detail.notes.map(n=><div className="comment-note" key={n.id}><p>{n.body}</p><small>{n.author}</small></div>)}<textarea aria-label="ملاحظة داخلية" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="هذه الملاحظة لا تُنشر…"/><button disabled={busy||!note.trim()} onClick={()=>mutate({action:"note",id:detail.comment.id,value:note})}>حفظ الملاحظة</button></>:<p>تظهر هنا بيانات الكاتب والمنشور والملاحظات بعد اختيار تعليق.</p>}</aside>
      </div>
      {detail&&<section className="panel-card"><h3>سجل الكاتب</h3>{detail.authorTotal===null?<p>هوية الكاتب غير متاحة من MCP؛ لا نستنتجها من الاسم ولا نجمع بيانات إضافية.</p>:<><p>{detail.authorTotal} تعليقًا على هذه الصفحة</p>{detail.history.map(c=><button key={c.id} onClick={()=>open(c.id)}>{c.message.slice(0,100)} · {time(c.created_time)}</button>)}</>}</section>}
    </>}
    {mode==="templates"&&<div className="comments-settings-grid"><form className="panel-card comments-form" onSubmit={e=>{e.preventDefault();mutate({action:"template",id:editTemplate?.id,input:{name,content:text,category,active:true}});}}><h2>{editTemplate?"تعديل القالب":"قالب رد جديد"}</h2><label>الاسم<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>التصنيف<input maxLength={80} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>محتوى الرد<textarea required rows={7} maxLength={8000} value={text} onChange={e=>setText(e.target.value)}/></label><button className="primary-button" disabled={busy}>حفظ القالب</button>{editTemplate&&<button type="button" onClick={resetTemplate}>قالب جديد</button>}<small>إدراج القالب لا يرسل الرد تلقائيًا.</small></form><section className="panel-card"><h2>مكتبة الردود · {templates.length}</h2>{templates.length?templates.map(t=><article className="comment-template" key={t.id}><div className="row-between"><h3>{t.name}</h3><span>{t.active?"نشط":"متوقف"}</span></div><p>{t.content}</p><small>{t.category} · استُخدم {t.usage_count} مرة</small><div><button onClick={()=>{setEditTemplate(t);setName(t.name);setText(t.content);setCategory(t.category);}}>تعديل</button><button disabled={busy} onClick={()=>mutate({action:"template",id:t.id,input:{name:t.name,content:t.content,category:t.category,active:!t.active}})}>{t.active?"تعطيل":"تفعيل"}</button></div></article>):<p>لا توجد قوالب. أضف أول رد محفوظ.</p>}</section></div>}
    {mode==="rules"&&<RuleManager admin={role==="admin"}/>}
    {(mode==="analytics"||mode==="status")&&metrics&&<section className="panel-card"><h2>{mode==="status"?"المزامنة والقدرات":"أداء الردود"}</h2><dl className="comments-analytics"><dt>إجمالي التعليقات</dt><dd>{metrics.total}</dd><dt>ردود يدوية مرسلة</dt><dd>{metrics.manual}</dd><dt>ردود آلية مرسلة</dt><dd>{metrics.automated}</dd><dt>متوسط زمن الرد</dt><dd>{metrics.avg_response_seconds===null?"لا توجد ردود مرسلة لاحتساب المتوسط":`${Math.round(metrics.avg_response_seconds/60)} دقيقة`}</dd><dt>آخر مزامنة</dt><dd>{metrics.lastSync?`${time(metrics.lastSync.started_at)} · ${metrics.lastSync.status}`:"لم تُنفذ مزامنة"}</dd><dt>آخر تعليق</dt><dd>{metrics.lastComment?time(metrics.lastComment):"لا يوجد"}</dd><dt>المزامنة الدورية</dt><dd>متوقفة · حدود الاستدعاء غير موثقة</dd><dt>Safe Mode للردود</dt><dd>مفعّل</dd></dl></section>}
    {mode==="analytics"&&<CommentsAnalytics/>}
    </>}
  </div>;
}
