"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import type { CommentsCapabilities } from "@/services/comments/provider";
export function CommentsHealth({compact=false}:{compact?:boolean}){
  const [caps,setCaps]=useState<(CommentsCapabilities&{flags?:{replies:boolean;autoReplies:boolean;automation:boolean}})|null>(null);const [metrics,setMetrics]=useState<{today:number;needs_reply:number;sent:number;failed:number;lastSync:{status:string;started_at:string}|null;lastComment:string|null}|null>(null);const [error,setError]=useState(false);
  useEffect(()=>{Promise.all([fetch("/api/comments?view=capabilities"),fetch("/api/comments?view=metrics")]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error();setCaps(await a.json());setMetrics(await b.json());}).catch(()=>setError(true));},[]);
  return <section className="card" style={{margin:"20px 0"}}><div className="panel-heading"><h2>تعليقات Facebook</h2><Link href="/inbox">صندوق الوارد</Link></div>{error?<p>تعذر التحقق من وحدة التعليقات.</p>:!caps||!metrics?<p>جارٍ التحقق…</p>:<>{compact?<p>اليوم: {metrics.today} · تحتاج ردًا: {metrics.needs_reply} · مرسلة: {metrics.sent} · فاشلة: {metrics.failed}</p>:<><div className="integration-row"><span>قراءة التعليقات / الردود</span><strong>{caps.read?"Available":"Unavailable"} / {caps.repliesRead?"Available":"Unavailable"}</strong></div><div className="integration-row"><span>الرد / الإخفاء / Webhook</span><strong>{caps.reply?"Available":"Unavailable"} / {caps.hide?"Available":"Unavailable"} / {caps.webhook?"Available":"Unverified"}</strong></div><div className="integration-row"><span>المزامنة الدورية</span><strong>مفعّلة عبر عامل النظام</strong></div><div className="integration-row"><span>آخر مزامنة</span><strong>{metrics.lastSync?`${metrics.lastSync.status} · ${new Date(metrics.lastSync.started_at).toLocaleString("ar-SA",{timeZone:"Asia/Riyadh"})}`:"لم تُنفذ"}</strong></div><div className="integration-row"><span>آخر تعليق</span><strong>{metrics.lastComment?new Date(metrics.lastComment).toLocaleString("ar-SA",{timeZone:"Asia/Riyadh"}):"لا يوجد"}</strong></div></>}<p>الرد اليدوي: {caps.reply&&caps.flags?.replies?"مفعّل":"متوقف"} · الرد التلقائي: {caps.flags?.automation&&caps.flags?.autoReplies&&caps.flags?.replies?"مفعّل":"متوقف"}</p></>}</section>;
}
