import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { assertDisposableDatabase } from './database-safety';
import { leadBulkAssignmentQuery,leadBulkAssignmentSchema } from '../src/services/leads-bulk';
import { loadLeadAssignmentAuthorization } from '../src/services/leads-assignment-authorization';

test('isolated assignment gates every row, current authorization, concurrent versions and atomic audit',{skip:!process.env.TEST_DATABASE_URL},async()=>{
  assertDisposableDatabase(process.env.TEST_DATABASE_URL,process.env.DISPOSABLE_TEST_DATABASE_HOST,process.env.DATABASE_URL);
  process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;
  const {getDb}=await import('../src/db');const db=getDb();
  const page=randomUUID(),outside=randomUUID(),member=randomUUID();
  const ids=[randomUUID(),randomUUID(),randomUUID(),randomUUID()];
  for(const target of [page,outside])await db.execute(sql`insert into facebook_pages(id,name,facebook_page_id) values(${target}::uuid,'Assignment QA',${`qa-${target}`})`);
  await db.execute(sql`insert into users(id,email,name,role) values(${member}::uuid,${`${member}@example.test`},'Assignment QA','editor')`);
  const scopeValue=JSON.stringify({unrestricted:false,pageIds:[page],accountIds:[]});
  await db.execute(sql`insert into settings(key,value) values(${`user_access_scope:${member}`},${scopeValue})`);
  for(const [index,lead] of ids.entries())await db.execute(sql`insert into leads(id,page_id,name) values(${lead}::uuid,${index===2?outside:index===3?null:page}::uuid,'Assignment QA synthetic')`);
  const snapshot=async()=>(await db.execute(sql`select id,assigned_to,updated_at::text as version from leads where id in (${sql.join(ids.map(id=>sql`${id}::uuid`),sql`, `)}) order by id`)).rows;
  const before=await snapshot();
  const item=(id:string)=>({id,expectedUpdatedAt:String(before.find(row=>row.id===id)!.version)});
  const target=await loadLeadAssignmentAuthorization(member);assert.ok(target);
  const execute=async(selected:ReturnType<typeof item>[],assignedTo:string|null=member,auth=target,scope:ReadonlySet<string>|null=new Set([page]))=>(await db.execute(leadBulkAssignmentQuery(leadBulkAssignmentSchema.parse({assignedTo,leads:selected}),scope,'assignment-qa@example.test',assignedTo?auth:null))).rows[0];
  assert.equal((await execute([item(ids[0]),item(ids[2])])).changed,0);
  assert.equal((await execute([item(ids[0]),item(ids[2])],member,target,null)).changed,0);
  assert.equal((await execute([item(ids[0]),item(ids[3])],member,target,null)).changed,0);
  assert.equal((await execute([item(ids[0]),{...item(ids[1]),expectedUpdatedAt:'2020-01-01T00:00:00Z'}])).changed,0);
  assert.deepEqual(await snapshot(),before);
  await db.execute(sql`update settings set value=${JSON.stringify({unrestricted:false,pageIds:[]})} where key=${`user_access_scope:${member}`}`);
  assert.equal((await execute([item(ids[0]),item(ids[1])])).changed,0);
  await db.execute(sql`update settings set value=${scopeValue} where key=${`user_access_scope:${member}`}`);
  await db.execute(sql`update users set role='viewer' where id=${member}::uuid`);
  assert.equal((await execute([item(ids[0]),item(ids[1])])).changed,0);
  await db.execute(sql`update users set role='editor',is_active=false where id=${member}::uuid`);
  assert.equal((await execute([item(ids[0]),item(ids[1])])).changed,0);
  await db.execute(sql`update users set is_active=true where id=${member}::uuid`);
  const concurrent=await Promise.all([execute([item(ids[0]),item(ids[1])]),execute([item(ids[1]),item(ids[0])])]);
  assert.deepEqual(concurrent.map(row=>row.changed).sort(),[0,2]);
  assert.deepEqual(concurrent.map(row=>row.audited).sort(),[0,2]);
  const assigned=await snapshot();
  for(const id of ids.slice(0,2))assert.equal(assigned.find(row=>row.id===id)!.assigned_to,member);
  for(const id of ids.slice(2))assert.equal(assigned.find(row=>row.id===id)!.assigned_to,null);
  const clearing=ids.slice(0,2).map(id=>({id,expectedUpdatedAt:String(assigned.find(row=>row.id===id)!.version)}));
  assert.equal((await execute(clearing,null)).changed,2);
  assert.equal((await execute(clearing,null)).changed,0);
  const audits=await db.execute(sql`select metadata from activity_logs where action='lead.assigned' and entity_id in (${sql.join(ids.map(id=>sql`${id}::uuid`),sql`, `)})`);
  assert.equal(audits.rows.length,4);for(const row of audits.rows)assert.equal((row.metadata as {bulk:boolean}).bulk,true);
});
