"use client";
import { useEffect,useState } from "react";
import { toast } from "../../ui/feedback";
function b64(v:string){const p="=".repeat((4-v.length%4)%4);const s=(v+p).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(s);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export function PushSettings(){
 const [supported,setSupported]=useState(false),[active,setActive]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{setSupported("serviceWorker"in navigator&&"PushManager"in window&&"Notification"in window);if(!("serviceWorker"in navigator))return;navigator.serviceWorker.register("/sw.js").then(async r=>setActive(Boolean(await r.pushManager.getSubscription()))).catch(()=>{});fetch("/api/push").then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>setConfigured(false))},[]);
 async function enable(){setBusy(true);let created:PushSubscription|null=null;try{const response=await fetch("/api/push");const d=await response.json();if(!response.ok||!d.configured||!d.publicKey)throw new Error("إشعارات Push غير مهيأة بعد");const perm=await Notification.requestPermission();if(perm!=="granted")throw new Error("لم يتم السماح بالإشعارات");const reg=await navigator.serviceWorker.ready;const existing=await reg.pushManager.getSubscription();const sub=existing??await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(d.publicKey)});if(!existing)created=sub;const r=await fetch("/api/push",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(sub.toJSON())});if(!r.ok)throw new Error("تعذر حفظ الاشتراك");setActive(true);toast("تم تفعيل إشعارات Push","success")}catch(e){if(created)await created.unsubscribe().catch(()=>false);toast(e instanceof Error?e.message:"تعذر التفعيل","error")}finally{setBusy(false)}}
 async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub){const response=await fetch("/api/push",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});if(!response.ok)throw new Error("تعذر إيقاف الاشتراك. حاول مرة أخرى.");if(!await sub.unsubscribe())throw new Error("تعذر إلغاء اشتراك الجهاز")}setActive(false);toast("تم إيقاف إشعارات Push")}catch(e){toast(e instanceof Error?e.message:"تعذر إيقاف Push","error")}finally{setBusy(false)}}
 return <section className="settings-card"><div><h3>إشعارات Push</h3><p className="muted">استقبل تنبيهات النظام على هذا الجهاز حتى عندما لا تكون الصفحة مفتوحة.</p></div>{!supported?<div className="alert alert-warning">هذا المتصفح لا يدعم Web Push.</div>:configured===false&&!active?<div className="alert alert-warning">إشعارات Push غير مهيأة بعد.</div>:<button className={active?"btn btn-secondary":"btn btn-primary"} disabled={busy||configured===null} onClick={active?disable:enable}>{active?"إيقاف Push على هذا الجهاز":configured===null?"جارٍ التحقق من إعداد Push…":"تفعيل Push على هذا الجهاز"}</button>}</section>
}
