"use client";
import { useEffect,useState } from "react";
import { toast } from "../../ui/feedback";
function b64(v:string){const p="=".repeat((4-v.length%4)%4);const s=(v+p).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(s);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export function PushSettings(){
 const [supported,setSupported]=useState(false),[active,setActive]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{setSupported("serviceWorker"in navigator&&"PushManager"in window&&"Notification"in window);if(!("serviceWorker"in navigator))return;navigator.serviceWorker.register("/sw.js").then(async r=>setActive(Boolean(await r.pushManager.getSubscription()))).catch(()=>{});fetch("/api/push").then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>setConfigured(false))},[]);
 async function enable(){setBusy(true);try{const d=await fetch("/api/push").then(r=>r.json());if(!d.publicKey)throw new Error("مفاتيح Push لم تُضف إلى Vercel بعد");const perm=await Notification.requestPermission();if(perm!=="granted")throw new Error("لم يتم السماح بالإشعارات");const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(d.publicKey)});const r=await fetch("/api/push",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(sub.toJSON())});if(!r.ok)throw new Error("تعذر حفظ الاشتراك");setActive(true);toast("تم تفعيل إشعارات Push","success")}catch(e){toast(e instanceof Error?e.message:"تعذر التفعيل","error")}finally{setBusy(false)}}
 async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub){await fetch("/api/push",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe()}setActive(false);toast("تم إيقاف إشعارات Push")}finally{setBusy(false)}}
 return <section className="settings-card"><div><h3>إشعارات Push</h3><p className="muted">استقبل تنبيهات النظام على هذا الجهاز حتى عندما لا تكون الصفحة مفتوحة.</p></div>{!supported?<div className="alert alert-warning">هذا المتصفح لا يدعم Web Push.</div>:configured===false?<div className="alert alert-warning">الكود جاهز. بقيت إضافة مفاتيح VAPID في Vercel لتفعيل Push.</div>:<button className={active?"btn btn-secondary":"btn btn-primary"} disabled={busy} onClick={active?disable:enable}>{active?"إيقاف Push على هذا الجهاز":"تفعيل Push على هذا الجهاز"}</button>}</section>
}