"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { LEAD_LABELS, LEAD_STAGES } from "@/services/leads-stages";

type PageOption = { id: string; name: string; platform: string };
export function LeadCreateForm({ pages }: { pages: PageOption[] }) {
  const router = useRouter();
  const requestId = useRef<string | null>(null);
  const submitting = useRef(false);
  const [form,setForm] = useState({ pageId: "", name: "", contact: "", status: "new", notes: "" });
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState("");
  const [savedId,setSavedId] = useState<string | null>(null);
  async function save(event: React.FormEvent) {
    event.preventDefault();
    if (submitting.current || savedId) return;
    submitting.current = true; setBusy(true); setError("");
    try {
      requestId.current ??= crypto.randomUUID();
      const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, id: requestId.current, contact: form.contact.trim() || null, notes: form.notes.trim() || null }) });
      const result = await response.json().catch(() => null);
      if (!response.ok) {
        setError(typeof result?.error === "string" ? result.error : "تعذر إضافة العميل. حاول مجددًا.");
        return;
      }
      // Navigate only to the UUID generated by this form, never a server-supplied URL.
      setSavedId(requestId.current); router.push(`/leads/${requestId.current}`); router.refresh();
    } catch { setError("تعذر الاتصال. بياناتك ما زالت في النموذج؛ أعد المحاولة."); }
    finally { submitting.current = false; setBusy(false); }
  }
  return <form className="card stack" onSubmit={save} style={{ gap: 16 }} aria-busy={busy}>
    <p className="muted">يُضاف العميل بمصدر «يدوي» دون إرسال رسالة أو إنشاء موعد متابعة تلقائيًا.</p>
    <fieldset disabled={busy || Boolean(savedId)} className="stack" style={{ border: 0, padding: 0, margin: 0, gap: 16 }}>
      <label>الصفحة المرتبطة<select value={form.pageId} required onChange={event => setForm(current => ({ ...current,pageId: event.target.value }))}><option value="" disabled>اختر صفحة</option>{pages.map(page => <option key={page.id} value={page.id}>{page.name} · {page.platform === "instagram" ? "Instagram" : "Facebook"}</option>)}</select></label>
      <label>اسم العميل<input value={form.name} required maxLength={160} autoComplete="name" onChange={event => setForm(current => ({ ...current,name: event.target.value }))}/></label>
      <label>معلومات التواصل<input value={form.contact} maxLength={500} placeholder="رقم الهاتف أو البريد أو وسيلة التواصل" onChange={event => setForm(current => ({ ...current,contact: event.target.value }))}/></label>
      <label>مرحلة العميل<select value={form.status} onChange={event => setForm(current => ({ ...current,status: event.target.value }))}>{LEAD_STAGES.map(stage => <option key={stage} value={stage}>{LEAD_LABELS[stage]}</option>)}</select></label>
      <label>ملاحظات داخلية<textarea value={form.notes} maxLength={10000} rows={5} onChange={event => setForm(current => ({ ...current,notes: event.target.value }))}/></label>
    </fieldset>
    {error ? <div className="alert alert-warning" role="alert">{error}</div> : null}
    {savedId ? <div className="alert alert-success" role="status">تمت إضافة العميل. جارٍ فتح التفاصيل… <Link href={`/leads/${savedId}`}>فتح العميل</Link></div> : null}
    <div className="actions"><button className="btn btn-primary" disabled={busy || Boolean(savedId) || !pages.length}>{busy ? "جارٍ الإضافة…" : "إضافة العميل"}</button><Link className="btn btn-secondary" href="/leads">العودة للعملاء</Link></div>
  </form>;
}
