"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";

const links = [["⌂", "الرئيسية", "/dashboard"], ["▤", "المنشورات", "/posts"], ["◷", "التقويم", "/calendar"], ["＋", "إنشاء منشور", "/posts/new"], ["f", "صفحات Facebook", "/pages"], ["⇧", "الاستيراد", "/import"], ["⌁", "السجلات", "/logs"], ["⚙", "الإعدادات", "/settings"]];

export function AppShell({ children, title, eyebrow }: { children: React.ReactNode; title: string; eyebrow?: string }) {
  const pathname = usePathname();
  return <div className="app-layout"><aside className="sidebar"><div className="app-brand"><div className="brand-mark">SP</div><div><strong>Social Publisher</strong><small>منصة النشر الذكي</small></div></div><nav className="side-nav" aria-label="التنقل الرئيسي">{links.map(([icon, label, href]) => <Link className={pathname === href || (href !== "/dashboard" && pathname.startsWith(href + "/")) ? "active" : ""} href={href} key={href}><span aria-hidden="true">{icon}</span>{label}</Link>)}</nav><div className="side-bottom"><div className="safe-mini"><span className="status-dot"/>وضع الاختبار<small>النشر الحقيقي متوقف</small></div><div className="profile-mini"><span className="avatar">م</span><div><strong>م. حبيب</strong><small>مشرف النظام</small></div><a href="/settings" aria-label="إعدادات الحساب">⚙</a></div><form method="post" action="/api/auth/logout"><button className="logout" type="submit">↪ تسجيل الخروج</button></form></div></aside><main className="app-main"><header className="topbar"><div className="crumbs"><span>Social Publisher</span><b>/</b><strong>{title}</strong></div><div className="topbar-actions"><a className="top-create" href="/posts/new">＋ إنشاء منشور</a><label className="search-box"><span>⌕</span><input aria-label="بحث" placeholder="بحث سريع..." /></label><button className="top-icon" aria-label="الإشعارات">♧<i /></button><span className="top-safe"><span className="status-dot"/>وضع الاختبار</span><div className="user-chip"><span className="avatar">م</span><span>المشرف</span><span className="chevron">⌄</span></div></div></header>{children}</main></div>
}
