"use client";
import { FormEvent, useState } from "react";
import { AppShell } from "../ui/app-shell";

type Preview={totalRows?:number;validRows?:number;missingImageRows?:number;errorRows?:number;duplicateRows?:number;rows?:Array<Record<string,unknown>>;error?:string};
export default function Import(){
 const [preview,setPreview]=useState<Preview|null>(null); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setPreview(null);const data=new FormData(e.currentTarget);try{const response=await fetch("/api/import/preview",{method:"POST",body:data});setPreview(await response.json())}catch{setPreview({error:"تعذر الاتصال بخدمة المعاينة"})}finally{setBusy(false)}}
 return <AppShell title="استيراد المحتوى" eyebrow="مصدر المحتوى"><div className="wizard-steps"><span className="active"><b>1</b> رفع الملف</span><span className={preview?"active":""}><b>2</b> مراجعة البيانات</span><span><b>3</b> الاستيراد</span></div><div className="import-layout"><section className="panel-card upload-card"><div className="section-heading"><div><span className="section-kicker">استيراد جماعي</span><h2>حوّل جدولك إلى محتوى جاهز</h2><p>ارفع ملف XLSX أو CSV لمعاينة الصفوف قبل تحويلها إلى مسودات.</p></div><span className="file-icon">↥</span></div><form className="upload-form" onSubmit={submit} encType="multipart/form-data"><label className="dropzone" htmlFor="file"><span>＋</span><strong>اختر ملف Excel أو اسحبه هنا</strong><small>الصيغ المدعومة: XLSX, XLS, CSV · حتى 10MB</small><input id="file" name="file" type="file" accept=".xlsx,.xls,.csv" required /></label><div className="upload-note"><span>i</span><p>ستتم معاينة البيانات أولاً ولن يُنشر أي محتوى تلقائياً.</p></div><button className="primary-button" type="submit" disabled={busy}>{busy?"جاري تحليل الملف…":"معاينة الملف"} <span>←</span></button></form>{preview&&<div className="import-result" aria-live="polite">{preview.error?<strong className="status-danger">{preview.error}</strong>:<><div className="result-grid"><span><b>{preview.totalRows??0}</b>صفًا</span><span><b>{preview.validRows??0}</b>صالح</span><span><b>{preview.missingImageRows??0}</b>بدون صورة</span><span><b>{preview.errorRows??0}</b>أخطاء</span><span><b>{preview.duplicateRows??0}</b>مكرر</span></div><strong className="result-title">تمت المعاينة بنجاح</strong><small>راجع النتيجة قبل حفظ المسودات.</small></>}</div>}</section><aside className="panel-card guide-card"><span className="section-kicker">إرشادات سريعة</span><h3>قبل الاستيراد</h3><div className="guide-step"><b>01</b><p><strong>النص</strong><small>عمود يحتوي على نص المنشور.</small></p></div><div className="guide-step"><b>02</b><p><strong>موعد النشر</strong><small>وقت اختياري بتوقيت الرياض.</small></p></div><div className="guide-step"><b>03</b><p><strong>المراجعة</strong><small>راجع الصفوف قبل حفظها.</small></p></div></aside></div></AppShell>
}
